# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Xianfeng Li
title: AI Algorithm Engineer
email: lockonlxf@163.com
# website: www.github.com/lockonlee

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  lockonlee
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: semanticscholar
#   icon: fa-solid fa-p
#   url: https://www.semanticscholar.org/author/2108137492
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/headshot.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Xianfeng Li.
  
  I'm an AI algorithm engineer at Hikvision Research Institute, worked with Dr. [Shicai Yang](https://www.semanticscholar.org/author/Shicai-Yang/2884262) 
  and Dr. [Weijie Chen](https://www.semanticscholar.org/author/Weijie-Chen/48994044). 
  
  I received the M.S. degree from School of Electronic and Information Engineering, South China University of Technology, Guangzhou, China in 2021, 
  advised by Prof. [Yuli Fu](https://www.researchgate.net/profile/Yuli-Fu).
  
  I received the B.S. degree from College of Information Science and Engineering,  National Huaqiao University, Xiamen, in 2018, 
  advised by Prof. [Huanqiang Zeng](https://www.semanticscholar.org/author/Huanqiang-Zeng/72910910).
  
  My research interests mainly focus on **Deep Learning** and its applications on **Computer Vision** and **Sciencs Analysis**.

  
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Hikvision Research Institute
        sub_title: AI Algorithm Engineer / Internship
        caption: July 2021 - Present / May 2020 - September 2020

#         description: | # this will include new lines to allow paragraphs
#             Every company need
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: South China University of Technology
        sub_title: School of Electronic and Information Engineering 
        caption: M.S. degree (September 2018 - June 2021)
#         description: | # this will include new lines to allow paragraphs
#           I started this project
          
      - layout: top-middle
        title: National Huaqiao University
        sub_title: College of Information Science and Engineering
        caption: B.S. degree (September 2014 - July 2018)
#         description: | # this will include new lines to allow paragraphs
            
  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Attnetion Diversication for Domain Generalization**

          Rang Meng*, **Xianfeng Li\***, Weijie Chen, Shicai Yang, Jie Song, Xinchao Wang, Lei Zhang, Mingli Song, Di Xie, Shiliang Pu

          *European Conference on Computer Vision (**ECCV 2022**)* \| \* Equal contribution
          
          [[Code](https://github.com/hikvision-research/DomainGeneralization)]
         
      - **Free Lunch for Cross-Domain Occluded Face Recognition without Source Data**
      
          Taoshan Zhang, Youjun Xiang, **Xianfeng Li**, Zichun Weng, Zhen Chen, Yuli Fu
          
          *IEEE International Conference on Acoustics, Speech and Signal Processing (**ICASSP 2022**)*
          
          [[Paper](https://ieeexplore.ieee.org/document/9746642)]
      - **Generalized Face Anti-Spoofing via Cross-Adversarial Disentanglement with Mixing Augmentation**
      
          Hanye Huang, Youjun Xiang, Guodong Yang, Lingling Lv, **Xianfeng Li**, Zichun Weng, Yuli Fu
          
          *IEEE International Conference on Acoustics, Speech and Signal Processing (**ICASSP 2022**)*
          
          [[Paper](https://ieeexplore.ieee.org/document/9746716)] 
          |
          
      - **A Free Lunch for Unsupervised Domain Adaptive Object Detection without Source Data**  
      
          **Xianfeng Li**, Weijie Chen, Di Xie, Shicai Yang, Peng Yuan, Shiliang Pu, Yueting Zhuang
          
          *AAAI Conference on Artificial Intelligence (**AAAI 2021**)*
          
          [[Paper](https://ojs.aaai.org/index.php/AAAI/article/view/17029)]&#8195;[[arXiv](https://arxiv.org/abs/2012.05400)]
      - **Combining Dynamic Image and Prediction Ensemble for Cross-Domain Face Anti-Spoofing**
      
          Lingling Lv, Youjun Xiang, **Xianfeng Li**, Hanye Huang, Rongju Ruan, Xiaoyan Xu, Yuli Fu
          
          *IEEE International Conference on Acoustics, Speech and Signal Processing (**ICASSP 2021**)*
          
          [[Paper](https://ieeexplore.ieee.org/document/9413926)]
      - **Saliency-Guided Transformer Network with Boosting Multi-Level Interaction for Blind Image Quality Assessment**
      
          Mengmeng Zhu, Yitian Li, **Xianfeng Li**, Tianwei Zhang
          
          *IEEE International Conference on Anti-counterfeiting, Security, and Identification (**ASID 2021**)* |
      - **A Novel Two-Pathway Encoder-Decoder Network for 3D Face Reconstruction**
      
          **Xianfeng Li**, Zichun Weng, Juntao Liang, Lei Cai, Youjun Xiang, Yuli Fu
          
          *IEEE International Conference on Acoustics, Speech and Signal Processing (**ICASSP 2020**)*
          
          [[Paper](https://ieeexplore.ieee.org/document/9053699)]
      - **Learning Semantic Representations via Joint 3D Face Reconstruction and Facial Attribute Estimation**
      
          Zichun Weng, Youjun Xiang, **Xianfeng Li**, Juntao Liang, Wanliang Huo, Yuli Fu
          
          *IEEE International Conference on Pattern Recognition (**ICPR 2020**)*
          
          [[Paper](https://ieeexplore.ieee.org/document/9412426)]
      - **Fast Compressed Sensing Recovery Using Generative Models and Sparse Deviations Modeling**
      
          Lei Cai, Yuli Fu, Youjun Xiang, Tao Zhu, **Xianfeng Li**, Huanqiang Zeng
          
          *IEEE International Conference on Visual Communications and Image Processing* (**VCIP 2020**)
          
          [[Paper](https://ieeexplore.ieee.org/document/9301808)]
  - title: Services
    layout: text
    content: | # this will include new lines to allow paragraphs
      Journal Reviewer of:
        - IEEE Transactions on Pattern Analysis and Machine Intelligence (TPAMI)
        - IEEE Transactions on Circuits and Systems for Video Technology (TCSVT)
        
      Conference Volunteer of:
        - IEEE International Symposium on Intelligent Signal Processing and Communication Systems (ISPACS 2017), Xiamen, China

#       Look at this cool image  

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

